"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
${custom.git_branch_clean}\
${custom.git_branch_dirty}\
$git_status\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$pixi\
$time\
 \
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "fg:color_yellow"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "fg:color_yellow"
style_root = "fg:color_yellow"
format = '[ $user ]($style)'

[directory]
style = "fg:color_aqua"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[custom.git_branch_clean]
command = 'git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD'
when = 'git rev-parse --is-inside-work-tree >/dev/null 2>&1 && test -z "$(git -c status.showUntrackedFiles=normal status --porcelain 2>/dev/null)"'
shell = ["bash", "--noprofile", "--norc"]
symbol = ""
style = "fg:color_fg0"
format = '[ $symbol $output ]($style)'

[custom.git_branch_dirty]
command = 'git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD'
when = 'git rev-parse --is-inside-work-tree >/dev/null 2>&1 && test -n "$(git -c status.showUntrackedFiles=normal status --porcelain 2>/dev/null)"'
shell = ["bash", "--noprofile", "--norc"]
symbol = ""
style = "fg:color_orange"
format = '[ $symbol $output ]($style)'

[git_status]
style = "fg:color_orange"
format = '[[($all_status$ahead_behind )](fg:color_orange)]($style)'

[nodejs]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[bun]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[c]
symbol = " "
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[cpp]
symbol = " "
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[rust]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[golang]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[php]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[java]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[kotlin]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[haskell]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[python]
symbol = ""
style = "fg:color_fg0"
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[docker_context]
symbol = ""
style = "fg:#83a598"
format = '[[ $symbol( $context) ](fg:#83a598)]($style)'

[conda]
style = "fg:#83a598"
format = '[[ $symbol( $environment) ](fg:#83a598)]($style)'

[pixi]
style = "fg:color_fg0"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0)]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:color_fg0"
format = '[[  $time ](fg:color_fg0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
